[bug] Add Meroxa-Account-UUID to CLI Requests
meroxa/meroxa-py pull request #37
Opened 2022-10-14 20:24 UTC by ericcheatham

Part of https://github.com/meroxa/turbine-project/issues/277

Meroxa-py client now requires `meroxa_account_uuid` which will then be set as a header value for  `Meroxa-Acconut-UUID`

2022-10-14 20:25 UTC, ericcheatham commented on src/meroxa/types.py
> -class ClientOptions:
This was not being used anywhere but was the cause of some weird import shadowing issues in Turbine-py

2022-10-17 17:14 UTC, ericcheatham commented on src/meroxa/applications.py
> +        git_sha: str = None,
`git_sha` can be omitted in in the response from the API. In the event that this happens we would get an error as we attempt to unpack the JSON response into an object that expects a particular named param to exist.

2022-10-17 17:17 UTC, ericcheatham commented on src/meroxa/applications.py
> +        git_sha: str = None,
This also addresses the following error:
```
Error: __init__() got an unexpected keyword argument 'created_at'
```

2022-10-18 07:51 UTC, jayjayjpg commented on src/meroxa/types.py
> -class ClientOptions:
Nice cleanup! :sparkles:

2022-10-18 07:52 UTC, jayjayjpg approved these changes
This reads great, thank you for the super quick update! :sparkles:

2022-10-18 07:52 UTC, jayjayjpg commented on src/meroxa/client.py
> +                    "Meroxa-Account-UUID": meroxa_account_uuid,
This reads great!

2022-10-18 17:38 UTC, janelletavares requested changes

2022-10-18 17:38 UTC, janelletavares commented on src/meroxa/client.py
> +                    "Meroxa-Account-UUID": meroxa_account_uuid,
i think there's a chance that meroxa_account_uuid is an empty string, so i think we should check that it's not empty before setting it.  this maybe the case if there's an older CLI but a new py app.

2022-10-19 17:38 UTC, janelletavares approved these changes

2022-10-19 17:42 UTC, merged